### ISSUE TITLE
527*: Replace SHA-1 and HMAC-SHA-1

### ISSUE THREAD

**Issue by seanturner** [seanturner/cmcbis#6]
Update 5272*bis to remove defaults of SHA-1 and HMAC-SHA-1.

**Comment by mandelj7** [comment]
References to SHA-1 and HMAC-SHA-1

https://seanturner.github.io/cmcbis/draft-mandel-lamps-rfc5272bis.html#name-identity-proof-control
https://seanturner.github.io/cmcbis/draft-mandel-lamps-rfc5272bis.html#section-6.3.1.2
https://seanturner.github.io/cmcbis/draft-mandel-lamps-rfc5272bis.html#section-6.7
https://seanturner.github.io/cmcbis/draft-mandel-lamps-rfc5272bis.html#section-6.15
 
https://seanturner.github.io/cmcbis/draft-mandel-lamps-rfc5274bis.html#name-cryptographic-algorithm-req

**Comment by seanturner** [comment]
Also see B.3:
https://seanturner.github.io/cmcbis/draft-mandel-lamps-rfc5272bis.html#name-direct-pop-for-an-rsa-certi
